// importamos la función `example`
import { orderAscDescByName } from '../src/data';

describe('orderAscDescByName', () => {
  it('debería ser una función', () => {
    expect(typeof orderAscDescByName).toBe('function');
  });

  describe('Es una funcion que ordena Ascendente y Descendente', () => {
    const input = [
      {
        name: 'Harry Potter',
        species: 'human',
        gender: 'male',
        house: 'Gryffindor',
        dateOfBirth: '31-07-1980',
        yearOfBirth: 1980,
        ancestry: 'half-blood',
        eyeColour: 'green',
        hairColour: 'black',
        wand: {
          wood: 'holly',
          core: 'phoenix feather',
          length: 11,
        },
        patronus: 'stag',
        hogwartsStudent: true,
        hogwartsStaff: false,
        actor: 'Daniel Radcliffe',
        alive: true,
        image: 'http://hp-api.herokuapp.com/images/harry.jpg',
      },
      {
        name: 'Hermione Granger',
        species: 'human',
        gender: 'female',
        house: 'Gryffindor',
        dateOfBirth: '19-09-1979',
        yearOfBirth: 1979,
        ancestry: 'muggleborn',
        eyeColour: 'brown',
        hairColour: 'brown',
        wand: {
          wood: 'vine',
          core: 'dragon heartstring',
          length: '',
        },
        patronus: 'otter',
        hogwartsStudent: true,
        hogwartsStaff: false,
        actor: 'Emma Watson',
        alive: true,
        image: 'http://hp-api.herokuapp.com/images/hermione.jpeg',
      },
      {
        name: 'Ron Weasley',
        species: 'human',
        gender: 'male',
        house: 'Gryffindor',
        dateOfBirth: '01-03-1980',
        yearOfBirth: 1980,
        ancestry: 'pure-blood',
        eyeColour: 'blue',
        hairColour: 'red',
        wand: {
          wood: 'willow',
          core: 'unicorn tail-hair',
          length: 14,
        },
        patronus: 'Jack Russell terrier',
        hogwartsStudent: true,
        hogwartsStaff: false,
        actor: 'Rupert Grint',
        alive: true,
        image: 'http://hp-api.herokuapp.com/images/ron.jpg',
      }];
    const output1 = [{
      name: 'Harry Potter',
      species: 'human',
      gender: 'male',
      house: 'Gryffindor',
      dateOfBirth: '31-07-1980',
      yearOfBirth: 1980,
      ancestry: 'half-blood',
      eyeColour: 'green',
      hairColour: 'black',
      wand: {
        wood: 'holly',
        core: 'phoenix feather',
        length: 11,
      },
      patronus: 'stag',
      hogwartsStudent: true,
      hogwartsStaff: false,
      actor: 'Daniel Radcliffe',
      alive: true,
      image: 'http://hp-api.herokuapp.com/images/harry.jpg',
    },
    {
      name: 'Hermione Granger',
      species: 'human',
      gender: 'female',
      house: 'Gryffindor',
      dateOfBirth: '19-09-1979',
      yearOfBirth: 1979,
      ancestry: 'muggleborn',
      eyeColour: 'brown',
      hairColour: 'brown',
      wand: {
        wood: 'vine',
        core: 'dragon heartstring',
        length: '',
      },
      patronus: 'otter',
      hogwartsStudent: true,
      hogwartsStaff: false,
      actor: 'Emma Watson',
      alive: true,
      image: 'http://hp-api.herokuapp.com/images/hermione.jpeg',
    },
    {
      name: 'Ron Weasley',
      species: 'human',
      gender: 'male',
      house: 'Gryffindor',
      dateOfBirth: '01-03-1980',
      yearOfBirth: 1980,
      ancestry: 'pure-blood',
      eyeColour: 'blue',
      hairColour: 'red',
      wand: {
        wood: 'willow',
        core: 'unicorn tail-hair',
        length: 14,
      },
      patronus: 'Jack Russell terrier',
      hogwartsStudent: true,
      hogwartsStaff: false,
      actor: 'Rupert Grint',
      alive: true,
      image: 'http://hp-api.herokuapp.com/images/ron.jpg',
    }];
    const output2 = [{
      name: 'Ron Weasley',
      species: 'human',
      gender: 'male',
      house: 'Gryffindor',
      dateOfBirth: '01-03-1980',
      yearOfBirth: 1980,
      ancestry: 'pure-blood',
      eyeColour: 'blue',
      hairColour: 'red',
      wand: {
        wood: 'willow',
        core: 'unicorn tail-hair',
        length: 14,
      },
      patronus: 'Jack Russell terrier',
      hogwartsStudent: true,
      hogwartsStaff: false,
      actor: 'Rupert Grint',
      alive: true,
      image: 'http://hp-api.herokuapp.com/images/ron.jpg',
    },
    {
      name: 'Hermione Granger',
      species: 'human',
      gender: 'female',
      house: 'Gryffindor',
      dateOfBirth: '19-09-1979',
      yearOfBirth: 1979,
      ancestry: 'muggleborn',
      eyeColour: 'brown',
      hairColour: 'brown',
      wand: {
        wood: 'vine',
        core: 'dragon heartstring',
        length: '',
      },
      patronus: 'otter',
      hogwartsStudent: true,
      hogwartsStaff: false,
      actor: 'Emma Watson',
      alive: true,
      image: 'http://hp-api.herokuapp.com/images/hermione.jpeg',
    },
    {
      name: 'Harry Potter',
      species: 'human',
      gender: 'male',
      house: 'Gryffindor',
      dateOfBirth: '31-07-1980',
      yearOfBirth: 1980,
      ancestry: 'half-blood',
      eyeColour: 'green',
      hairColour: 'black',
      wand: {
        wood: 'holly',
        core: 'phoenix feather',
        length: 11,
      },
      patronus: 'stag',
      hogwartsStudent: true,
      hogwartsStaff: false,
      actor: 'Daniel Radcliffe',
      alive: true,
      image: 'http://hp-api.herokuapp.com/images/harry.jpg',
    },
    ];
    expect(orderAscDescByName(input, 'A-Z')).toEqual(output1);
    expect(orderAscDescByName(input, 'Z-A')).toEqual(output2);
  });
});
